PL_MVC/Controllers/AlumnoController.cs
using Microsoft.Ajax.Utilities;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
//using BL;
//using ML;

namespace PL_MVC.Controllers
{
    public class AlumnoController : Controller
    {
        // GET: Alumno

        //[HttpPost]
        //[HttpPut]
        //[HttpDelete]
        //[HttpPatch]
        [HttpGet]
        public ActionResult GetAll()
        {
            ML.Alumno alumno = new ML.Alumno();
            ML.Result result = BL.Alumno.GetAllEF();
             
            if (result.Correct)
            {
                alumno.Alumnos = result.Objects;
                //reusltado = a + b;
            }
            else
            {
                ViewBag.Message = "Ocurrio un error al realizar la consulta";
            }

            return View(alumno);
        }

        [HttpGet]
        public ActionResult Form(int? IdAlumno)
        {
            ML.Result resultSemestre = BL.Semestre.GetAll();
            ML.Alumno alumno = new ML.Alumno();
            alumno.Semestre = new ML.Semestre();//inicializando
            if (IdAlumno == null)
            {
                alumno.Semestre.Semestres = resultSemestre.Objects;
                return View(alumno);
            }
            else
            {
                
                //GetbyId
                ML.Result result = BL.Alumno.GetByIdEF(IdAlumno.Value);
                
                if (result.Correct)
                {
                    alumno = (ML.Alumno)result.Object;

                }
                else
                {
                    ViewBag.Message = "Ocurrio un error al consultar el alummno seleccionado";
                }
                return View(alumno);
            }
            
        }

        [HttpPost]
        public ActionResult Form(ML.Alumno alumno)
        {
            if (alumno.IdAlumno == 0)
            {
                //add
                //ml.result = agergar
                ML.Result result = BL.Alumno.AddEF(alumno);

                if (result.Correct)
                {
                    ViewBag.Message = result.Message;
                }
                else
                {
                    ViewBag.Message = "Error: " + result.Message;
                }
            }
            else
            {
                ML.Result result = BL.Alumno.AddEF(alumno);

                if (result.Correct)
                {
                    ViewBag.Message = result.Message;
                }
                else
                {
                    ViewBag.Message = "Error: " + result.Message;
                }
            }

            return PartialView("Modal");
        }

        //DELETE
    }
}

PL_MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PL_MVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Hola Generación de octubre :D";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

PL_MVC/Views/Alumno/Form.cshtml
@model ML.Alumno
@{
    ViewBag.Title = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <h2>Form</h2>
    <div class="row">

        <div class="col-md-12">

            @using (Html.BeginForm("Form", "Alumno", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {

                <div class="form-horizontal">

                    <div class="form-group">

                        <div class="col-md-3">

                            @Html.LabelFor(model => model.IdAlumno, new { @class = "hidden" })

                            @Html.TextBoxFor(model => model.IdAlumno, new { @class = "hidden form-control" })

                            @Html.ValidationMessageFor(model => model.IdAlumno)

                        </div>

                    </div>

                    <div class="form-group">

                        <div class="col-md-3">

                            @Html.LabelFor(model => model.Nombre)

                            @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control", @id = "txtNombre" })

                            @Html.ValidationMessageFor(model => model.Nombre)

                        </div>

                    </div>
                    <div class="form-group">

                        <div class="col-md-3">

                            @Html.LabelFor(model => model.ApellidoPaterno)

                            @Html.TextBoxFor(model => model.ApellidoPaterno, new { @class = "form-control" })

                            @Html.ValidationMessageFor(model => model.ApellidoPaterno)

                        </div>

                    </div>
                    <div class="form-group">

                        <div class="col-md-3">

                            @Html.LabelFor(model => model.ApellidoMaterno)

                            @Html.TextBoxFor(model => model.ApellidoMaterno, new { @class = "form-control" })

                            @Html.ValidationMessageFor(model => model.ApellidoMaterno)

                        </div>

                    </div>
                    <div class="form-group">

                        <div class="col-md-3">

                            @Html.LabelFor(model => model.FechaNacimiento)

                            @Html.TextBoxFor(model => model.FechaNacimiento, new { @class = "form-control" })

                            @Html.ValidationMessageFor(model => model.FechaNacimiento)

                        </div>

                    </div>
                    <div class="form-group">

                        <div class="col-md-3">

                            @Html.LabelFor(model => model.Genero)

                            @Html.TextBoxFor(model => model.Genero, new { @class = "form-control" })

                            @Html.ValidationMessageFor(model => model.Genero)

                        </div>

                    </div>

                    <div class="form-group">

                        <div class="col-md-3">

                            @Html.LabelFor(model => model.Semestre.IdSemestre)

                            @*@Html.TextBoxFor(model => model.Semestre.IdSemestre, new { @class = "form-control" })*@

                            @Html.DropDownListFor(model => model.Semestre.IdSemestre, new SelectList(Model.Semestre.Semestres, "IdSemestre", "Nombre"), "Selecciona un semestre", new { @class = "form-control" })

                            @*<select>
                                <option>Seleccione un semestre</option>
                                <option>Primero</option>
                                <option>Segundo</option>
                                <option>Tercero</option>
                                <option>Cuarto</option>
                            </select>*@

                            @Html.ValidationMessageFor(model => model.Semestre.IdSemestre)

                        </div>

                    </div>




                    <div class="form-group">

                        <div class="col-md-3">

                            <input type="submit" value="Guardar" class="btn btn-success" />

                            @Html.ActionLink("Regresar", "GetAll", "Alumno", htmlAttributes: new { @class = "btn btn-danger" })

                        </div>

                    </div>

                </div>

            }

        </div>

    </div>
</div>

PL_MVC/Views/Alumno/GetAll.cshtml
@model ML.Alumno
@{
    ViewBag.Title = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <h2>Alumno</h2>
    <p>Aqui puede ver, editar o agrgar a un alumno</p>
    <p>Para agregar un alumno presione el boton verde</p>
    <p>Para editar un alumno presione el boton amarillo</p>
    <p>Para eliminar un alumno presione el boton rojo</p>

    <div class="row">
        <div style="float:right">
            @Html.ActionLink("+", "Form", "Alumno", htmlAttributes: new { @class = "btn btn-success" })

        </div>
    </div>

    <hr />
    <div class="row">

        <table class="table table-responsive">
            <thead>
                <tr>
                    <th>Editar</th>
                    <th class="hidden">IdAlumno</th>
                    <th>Nombre</th>
                    @*<th>Apellido Paterno</th>
                        <th>Apellido Paterno</th>*@
                    <th>Fecha Nacimiento</th>
                    <th>Genero</th>
                    <th>Semestre</th>
                    <th>Eliminar</th>
                </tr>

            </thead>
            <tbody>
                @foreach (ML.Alumno alumno in Model.Alumnos)
                {
                    <tr>
                        <td class="text-center"><a class="btn btn-warning glyphicon glyphicon-edit" href="@Url.Action("Form", "Alumno", new { IdAlumno = alumno.IdAlumno})"></a></td>
                        <td class="hidden">@alumno.IdAlumno</td>
                        <td>@alumno.Nombre @alumno.ApellidoPaterno @alumno.ApellidoMaterno</td>
                        @*<td></td>
                            <td></td>*@
                        <td>@alumno.FechaNacimiento</td>
                        <td>@alumno.Genero</td>
                        <td class="hidden">@alumno.Semestre.IdSemestre</td>
                        <td >@alumno.Semestre.Nombre</td>
                        <td class="text-center"><a class="btn btn-danger glyphicon glyphicon-trash" href="@Url.Action("Delete", "Alumno", new { IdAlumno = alumno.IdAlumno })" onclick="return confirm('Estas seguro que deseas eliminar este registro?');"></a></td>


                    </tr>

                }
            </tbody>
        </table>
    </div>
</div>

PL_MVC/Views/Alumno/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Message</h5>
            </div>
            <div class="modal-footer">
                
                @Html.ActionLink("Regresar", "GetAll", "Alumno", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

<script>
    $('#modalValidacion').modal();
</script>

PL_MVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

PL_MVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

PL_MVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

PL_MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Alumno", "GetAll", "Alumno")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>